# Generated by Django 4.0.2 on 2022-10-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
