# Generated by Django 4.0.2 on 2022-11-01 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_message_user_room_host_room_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='host',
            new_name='admin',
        ),
    ]
