# Generated by Django 4.0.2 on 2022-11-01 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_host_room_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='admin',
            new_name='host',
        ),
    ]
