# Generated by Django 4.0.2 on 2022-12-07 15:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_rename_admin_room_host'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Post',
        ),
    ]
