# Generated by Django 4.0.2 on 2022-12-13 09:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_rename_message_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='room',
            new_name='group',
        ),
    ]
