# Generated by Django 4.0.2 on 2023-01-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_likepost_post_no_of_likes_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileimg',
            new_name='profile_img',
        ),
    ]
