# Generated by Django 4.0.2 on 2023-01-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
