# Generated by Django 4.0.2 on 2023-01-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
